file_format: "1"
id: corne_antar
name: Corne_antar
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - studio
siblings:
  - corne_antar_left
  - corne_antar_right
